-- Insertar tipos de vehículo
INSERT INTO tipo_vehiculo (nombre_tipo, descripcion, estado) VALUES
('Auto', 'Vehículo particular de 4 ruedas', 'activo'),
('Moto', 'Motocicleta de dos ruedas', 'activo'),
('Camioneta', 'Vehículo utilitario', 'activo'),
('Bicicleta', 'Vehículo sin motor', 'activo'),
('Pickup', 'Vehículo de carga ligera', 'inactivo');

-- Insertar tarifas (una por tipo de vehículo)
INSERT INTO tarifa (id_tipo_vehiculo, tarifa_por_hora, tarifa_minima, tiempo_minimo, tiempo_maximo) VALUES
(1, 10.00, 5.00, 30, 1440),
(2, 5.00, 2.00, 30, 1440),
(3, 12.00, 6.00, 30, 1440),
(4, 2.00, 1.00, 15, 720),
(5, 15.00, 8.00, 60, 1440);

-- Insertar clientes
INSERT INTO cliente (nombre, telefono, correo) VALUES
('Luis Ramírez', '555123456', 'luis@gmail.com'),
('Ana Gómez', '555234567', 'ana@hotmail.com'),
('Carlos Pérez', '555345678', 'carlos@yahoo.com'),
('Laura Torres', '555456789', 'laura@gmail.com'),
('Pedro Castillo', '555567890', 'pedro@outlook.com'),
('María López', '555678901', 'maria@gmail.com'),
('José Hernández', '555789012', 'jose@hotmail.com'),
('Sofía Ruiz', '555890123', 'sofia@yahoo.com'),
('Diego Martínez', '555901234', 'diego@gmail.com'),
('Valeria Méndez', '555012345', 'valeria@outlook.com');

-- Insertar espacios de parqueo
INSERT INTO espacio_parqueo (numero_espacio, disponible, ubicacion) VALUES
(101, true, 'Zona A'),
(102, true, 'Zona A'),
(103, true, 'Zona A'),
(201, false, 'Zona B'),
(202, false, 'Zona B'),
(203, true, 'Zona B'),
(301, true, 'Zona C'),
(302, true, 'Zona C'),
(401, false, 'Zona D'),
(402, true, 'Zona D');

-- Insertar tickets
INSERT INTO ticket (id_cliente, id_tipo_vehiculo, fecha, hora_entrada, hora_salida, estado, costo_total) VALUES
(1, 1, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '60 MINUTES', CURRENT_TIMESTAMP, 'finalizado', 26.84),
(2, 2, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '63 MINUTES', NULL, 'activo', NULL),
(3, 3, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '66 MINUTES', CURRENT_TIMESTAMP, 'finalizado', 42.7),
(4, 4, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '69 MINUTES', NULL, 'activo', NULL),
(5, 5, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '72 MINUTES', CURRENT_TIMESTAMP, 'finalizado', 43.64),
(6, 1, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '75 MINUTES', NULL, 'activo', NULL),
(7, 2, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '78 MINUTES', CURRENT_TIMESTAMP, 'finalizado', 31.69),
(8, 3, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '81 MINUTES', NULL, 'activo', NULL),
(9, 4, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '84 MINUTES', CURRENT_TIMESTAMP, 'finalizado', 21.58),
(10, 5, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '87 MINUTES', NULL, 'activo', NULL),
(1, 1, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '90 MINUTES', CURRENT_TIMESTAMP, 'finalizado', 36.92),
(2, 2, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '93 MINUTES', NULL, 'activo', NULL),
(3, 3, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '96 MINUTES', CURRENT_TIMESTAMP, 'finalizado', 28.56),
(4, 4, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '99 MINUTES', NULL, 'activo', NULL),
(5, 5, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '102 MINUTES', CURRENT_TIMESTAMP, 'finalizado', 30.99),
(6, 1, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '105 MINUTES', NULL, 'activo', NULL),
(7, 2, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '108 MINUTES', CURRENT_TIMESTAMP, 'finalizado', 45.1),
(8, 3, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '111 MINUTES', NULL, 'activo', NULL),
(9, 4, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '114 MINUTES', CURRENT_TIMESTAMP, 'finalizado', 38.75),
(10, 5, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '117 MINUTES', NULL, 'activo', NULL),
(1, 1, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '120 MINUTES', CURRENT_TIMESTAMP, 'finalizado', 48.39),
(2, 2, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '123 MINUTES', NULL, 'activo', NULL),
(3, 3, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '126 MINUTES', CURRENT_TIMESTAMP, 'finalizado', 35.66),
(4, 4, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '129 MINUTES', NULL, 'activo', NULL),
(5, 5, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '132 MINUTES', CURRENT_TIMESTAMP, 'finalizado', 28.94),
(6, 1, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '135 MINUTES', NULL, 'activo', NULL),
(7, 2, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '138 MINUTES', CURRENT_TIMESTAMP, 'finalizado', 46.12),
(8, 3, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '141 MINUTES', NULL, 'activo', NULL),
(9, 4, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '144 MINUTES', CURRENT_TIMESTAMP, 'finalizado', 55.04),
(10, 5, CURRENT_DATE, CURRENT_TIMESTAMP - INTERVAL '147 MINUTES', NULL, 'activo', NULL);

-- Insertar asignaciones de espacios
INSERT INTO asignacion_espacio (id_ticket, id_espacio, hora_inicio_asignacion, hora_fin_asignacion) VALUES
(1, 1, CURRENT_TIMESTAMP - INTERVAL '60 MINUTES', CURRENT_TIMESTAMP),
(2, 2, CURRENT_TIMESTAMP - INTERVAL '63 MINUTES', NULL),
(3, 3, CURRENT_TIMESTAMP - INTERVAL '66 MINUTES', CURRENT_TIMESTAMP),
(4, 4, CURRENT_TIMESTAMP - INTERVAL '69 MINUTES', NULL),
(5, 5, CURRENT_TIMESTAMP - INTERVAL '72 MINUTES', CURRENT_TIMESTAMP),
(6, 6, CURRENT_TIMESTAMP - INTERVAL '75 MINUTES', NULL),
(7, 7, CURRENT_TIMESTAMP - INTERVAL '78 MINUTES', CURRENT_TIMESTAMP),
(8, 8, CURRENT_TIMESTAMP - INTERVAL '81 MINUTES', NULL),
(9, 9, CURRENT_TIMESTAMP - INTERVAL '84 MINUTES', CURRENT_TIMESTAMP),
(10, 10, CURRENT_TIMESTAMP - INTERVAL '87 MINUTES', NULL),
(11, 1, CURRENT_TIMESTAMP - INTERVAL '90 MINUTES', CURRENT_TIMESTAMP),
(12, 2, CURRENT_TIMESTAMP - INTERVAL '93 MINUTES', NULL),
(13, 3, CURRENT_TIMESTAMP - INTERVAL '96 MINUTES', CURRENT_TIMESTAMP),
(14, 4, CURRENT_TIMESTAMP - INTERVAL '99 MINUTES', NULL),
(15, 5, CURRENT_TIMESTAMP - INTERVAL '102 MINUTES', CURRENT_TIMESTAMP),
(16, 6, CURRENT_TIMESTAMP - INTERVAL '105 MINUTES', NULL),
(17, 7, CURRENT_TIMESTAMP - INTERVAL '108 MINUTES', CURRENT_TIMESTAMP),
(18, 8, CURRENT_TIMESTAMP - INTERVAL '111 MINUTES', NULL),
(19, 9, CURRENT_TIMESTAMP - INTERVAL '114 MINUTES', CURRENT_TIMESTAMP),
(20, 10, CURRENT_TIMESTAMP - INTERVAL '117 MINUTES', NULL),
(21, 1, CURRENT_TIMESTAMP - INTERVAL '120 MINUTES', CURRENT_TIMESTAMP),
(22, 2, CURRENT_TIMESTAMP - INTERVAL '123 MINUTES', NULL),
(23, 3, CURRENT_TIMESTAMP - INTERVAL '126 MINUTES', CURRENT_TIMESTAMP),
(24, 4, CURRENT_TIMESTAMP - INTERVAL '129 MINUTES', NULL),
(25, 5, CURRENT_TIMESTAMP - INTERVAL '132 MINUTES', CURRENT_TIMESTAMP),
(26, 6, CURRENT_TIMESTAMP - INTERVAL '135 MINUTES', NULL),
(27, 7, CURRENT_TIMESTAMP - INTERVAL '138 MINUTES', CURRENT_TIMESTAMP),
(28, 8, CURRENT_TIMESTAMP - INTERVAL '141 MINUTES', NULL),
(29, 9, CURRENT_TIMESTAMP - INTERVAL '144 MINUTES', CURRENT_TIMESTAMP),
(30, 10, CURRENT_TIMESTAMP - INTERVAL '147 MINUTES', NULL);